// ─── GENERATE WITH AI ──────────────────────────────────────────────
// Reveals the user's own AI key via smartmatrix-auth (Service Binding, no
// keys ever touch this app's storage), asks it to write a ScriptForge .cfg
// template, then routes the raw result into the SAME import/editor flow
// used for manual .cfg uploads -- so the user reviews and edits before
// "Cargar Template" persists anything, and there's zero duplicated save logic.

const AI_MODELS_BY_PROVIDER = {
  perplexity: ['sonar', 'sonar-pro', 'sonar-reasoning-pro'],
  openai: ['gpt-4o', 'gpt-4o-mini', 'gpt-4.1', 'o3-mini'],
  anthropic: ['claude-3-5-sonnet-latest', 'claude-3-5-haiku-latest', 'claude-3-opus-latest']
};
const AI_PROVIDER_LABELS = { perplexity: 'Perplexity', openai: 'OpenAI', anthropic: 'Anthropic' };

let _aiProvidersStatus = null;

async function loadAiProviders() {
  const warningEl = document.getElementById('aiNoProviderWarning');
  const formEl = document.getElementById('aiFormWrapper');
  const providerSelect = document.getElementById('aiProviderSelect');
  const modelSelect = document.getElementById('aiModelSelect');

  try {
    const res = await fetch('/api/ai/providers');
    _aiProvidersStatus = res.ok ? await res.json() : {};
  } catch {
    _aiProvidersStatus = {};
  }

  const configured = Object.entries(_aiProvidersStatus || {}).filter(([, v]) => v && v.configured);

  if (configured.length === 0) {
    warningEl.classList.remove('hidden');
    formEl.classList.add('hidden');
    document.getElementById('aiGenerateConfirmBtn').disabled = true;
    return;
  }

  warningEl.classList.add('hidden');
  formEl.classList.remove('hidden');
  document.getElementById('aiGenerateConfirmBtn').disabled = false;

  providerSelect.innerHTML = configured
    .map(([id]) => `<option value="${id}">${AI_PROVIDER_LABELS[id] || id}</option>`)
    .join('');

  function refreshModels() {
    const provider = providerSelect.value;
    const preferred = _aiProvidersStatus[provider] && _aiProvidersStatus[provider].model;
    const models = AI_MODELS_BY_PROVIDER[provider] || [];
    modelSelect.innerHTML = models
      .map(m => `<option value="${m}" ${m === preferred ? 'selected' : ''}>${m}</option>`)
      .join('');
  }
  providerSelect.onchange = refreshModels;
  refreshModels();
}

document.getElementById('aiGenerateBtn').addEventListener('click', () => {
  document.getElementById('aiDescriptionInput').value = '';
  document.getElementById('aiLoading').classList.add('hidden');
  loadAiProviders();
  openModal('aiModal');
  setTimeout(() => document.getElementById('aiDescriptionInput').focus(), 220);
});

document.getElementById('aiGenerateConfirmBtn').addEventListener('click', async () => {
  const description = document.getElementById('aiDescriptionInput').value.trim();
  if (!description) { showToast('Describe what you need first', true); return; }

  const provider = document.getElementById('aiProviderSelect').value;
  const model = document.getElementById('aiModelSelect').value;
  const confirmBtn = document.getElementById('aiGenerateConfirmBtn');
  const loading = document.getElementById('aiLoading');

  confirmBtn.disabled = true;
  loading.classList.remove('hidden');

  try {
    const res = await fetch('/api/ai/generate-template', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ description, provider, model, categories: categories.map(c => c.id) })
    });
    const data = await res.json();
    if (!res.ok) throw new Error(data.error || 'Generation failed');

    closeModal('aiModal');

    // Reuse the exact same review/edit UI as a manual .cfg import.
    resetImportModal();
    document.getElementById('cfgEditor').value = data.content;
    document.getElementById('importModalSubtitle').textContent = 'Generated by AI — review and edit before saving';
    openModal('importModal');
  } catch (err) {
    showToast(err.message, true);
  } finally {
    confirmBtn.disabled = false;
    loading.classList.add('hidden');
  }
});
