name = "scriptforge"
main = "src/index.js"
compatibility_date = "2026-08-01"

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "scriptforge_kv"
id = "11bc44da7e6e4b2586e0d79c25abab6c"